courses = ['analysenumerique_001',
 'analysenumerique_002',
 'analysenumerique_003',
 'cpp_fr_001',
 'dsp_001',
 'dsp_002',
 'dsp_004',
 'dsp_005',
 'dsp_006',
 'geomatique_003',
 'hwts_001',
 'hwts_002',
 'initprogcpp_001',
 'microcontroleurs_003',
 'microcontroleurs_004',
 'microcontroleurs_005',
 'microcontroleurs_006',
 'progfun_002',
 'progfun_003',
 'structures_001',
 'structures_002',
 'structures_003',
 'venture_001',
 'villesafricaines_001',
 'villesafricaines_002',
 'villesafricaines_003']

dict_course_names = {'analysenumerique_001': 'AnNum 1',
 'analysenumerique_002': 'AnNum 2',
 'analysenumerique_003': 'AnNum 3',
 'cpp_fr_001': 'OOP',
 'dsp_001': 'DSP 1',
 'dsp_002': 'DSP 2',
 'dsp_004': 'DSP 4',
 'dsp_005': 'DSP 5',
 'dsp_006': 'DSP 6',
 'geomatique_003': 'Geomatique',
 'hwts_001': 'HWTS 1',
 'hwts_002': 'HWTS 2',
 'initprogcpp_001': 'InitProgC++',
 'microcontroleurs_003': 'Micro 3',
 'microcontroleurs_004': 'Micro 4',
 'microcontroleurs_005': 'Micro 5',
 'microcontroleurs_006': 'Micro 6',
 'progfun_002': 'ProgFun 2',
 'progfun_003': 'ProgFun 3',
 'structures_001': 'Structures 1',
 'structures_002': 'Structures 2',
 'structures_003': 'Structures 3',
 'venture_001': 'Venture 1',
 'villesafricaines_001' : 'Villes Africaines 1',
 'villesafricaines_002': 'Villes Africaines 2',
 'villesafricaines_003': 'Villes Africaines 3'}

feature_names_dict = {
 'total_clicks_Video.Load': 'Total Clicks Video Load',
 'weekly_prop_watched mean': 'Avg Watced Weekly Prop',
 'weekly_prop_watched std': 'Std Watched Weekly Prop',
 'weekly_prop_replayed mean': 'Avg Replayed Weekly Prop',
 'weekly_prop_replayed std': 'Std Replayed Weekly Prop',
 'weekly_prop_interrupted mean': 'Avg Interrupted Weekly Prop',
 'weekly_prop_interrupted std': 'Std Interrupted Weekly Prop',
 'total_clicks_Video': 'Total Clicks Video',
 'frequency_action_Video': 'Frequency Event Video',
 'frequency_action_Video.Load': 'Frequency Event Load',
 'frequency_action_Video.Play': 'Frequency Event Play',
 'frequency_action_Video.Pause': 'Frequency Event Pause',
 'frequency_action_Video.Stop': 'Frequency Event Stop',
 'frequency_action_Video.SeekBackward': 'Frequency Event SeekBackward',
 'frequency_action_Video.SeekForward': 'Frequency Event SeekForward',
 'frequency_action_Video.SpeedChange': 'Frequency Event SpeedChange',
 'seek_length mean': 'Avg Seek Length',
 'seek_length std': 'Std Seek Length',
 'pause_duration mean': 'Avg Pause Duration',
 'pause_duration std': 'Std Pause Duration',
 'time_speeding_up mean': 'Avg Time Speeding Up',
 'time_speeding_up std': 'Std Time Speeding Up',
 'regularity_peak_dayhour': 'Reg Peak Day Hour',
 'regularity_periodicity_m1': 'Reg Periodicity m1', 
 'delay_lecture': 'Delay Lecture',
 'total_clicks': 'Total Clicks',
 'number_sessions': 'Number of Sessions',
 'time_sessions sum': 'Total Time Sessions',
 'time_sessions mean': 'Avg Time Sessions',
 'time_between_sessions std': 'Std Time Between Sessions',
 'time_sessions std': 'Std Time Sessions',
 'total_clicks_weekday': 'Total Clicks Weekday',
 'total_clicks_weekend': 'Total Clicks Weekend',
 'ratio_clicks_weekend_day': 'Ratio Clicks Weekend Day',
 'total_clicks_video': 'Total Clicks video',
 'total_clicks_problem': 'Total Clicks Problem',
 'time_in__problem sum': 'Total Time Problem',
 'time_in__video sum': 'Total Time Video',
 'competency_strength': 'Competency Strength',
 'competency_alignment': 'Competency Alignment',
 'competency_anticipation': 'Competency Anticipation',
 'content_alignment': 'Content Alignment',
 'content_anticipation': 'Content Anticipation',
 'student_speed': 'Student Speed',
 'student_shape': 'Student Shape'
}

course_w_number_course = {'analysenumerique_001': 'Analyse Numérique',
 'analysenumerique_002': 'Analyse Numérique',
 'analysenumerique_003': 'Analyse Numérique',
 'cpp_fr_001': 'Programmation Orientée Objet',
 'dsp_001': 'Digital Signal Processing (DSP)',
 'dsp_002': 'Digital Signal Processing (DSP)',
 'dsp_004': 'Digital Signal Processing (DSP)',
 'dsp_005': 'Digital Signal Processing (DSP)',
 'dsp_006': 'Digital Signal Processing (DSP)',
 'geomatique_003': 'Éléments de Géomatique',
 'hwts_001': 'Household Water Treatment and Storage (HWTS)',
 'hwts_002': 'Household Water Treatment and Storage (HWTS)',
 'initprogcpp_001': 'ProgramProgrammation Orientée Objetmation en C++',
 'microcontroleurs_003': 'Comprendre les Microcontrôleurs',
 'microcontroleurs_004': 'Comprendre les Microcontrôleurs',
 'microcontroleurs_005': 'Comprendre les Microcontrôleurs',
 'microcontroleurs_006': 'Comprendre les Microcontrôleurs',
 'progfun_002': 'Functional Programming',
 'progfun_003': 'Functional Programming',
 'structures_001': 'L’Art des Structures I',
 'structures_002': 'L’Art des Structures I',
 'structures_003': 'L’Art des Structures I',
 'venture_001': 'Launching New Ventures',
 'villesafricaines_001' : 'Villes Africaines',
 'villesafricaines_002': 'Villes Africaines',
 'villesafricaines_003': 'Villes Africaines'}

topics_course = {'analysenumerique_001': 'Math',
 'analysenumerique_002': 'Math',
 'analysenumerique_003': 'Math',
 'cpp_fr_001': 'CS',
 'dsp_001': 'CS',
 'dsp_002': 'CS',
 'dsp_004': 'CS',
 'dsp_005': 'CS',
 'dsp_006': 'CS',
 'geomatique_003': 'Math',
 'hwts_001': 'NS',
 'hwts_002': 'NS',
 'initprogcpp_001': 'CS',
 'microcontroleurs_003': 'Eng',
 'microcontroleurs_004': 'Eng',
 'microcontroleurs_005': 'Eng',
 'microcontroleurs_006': 'Eng',
 'progfun_002': 'CS',
 'progfun_003': 'CS',
 'structures_001': 'Arch',
 'structures_002': 'Arch',
 'structures_003': 'Arch',
 'venture_001': 'Bus',
 'villesafricaines_001' : 'SS',
 'villesafricaines_002': 'SS',
 'villesafricaines_003': 'SS'}

language_and_level_course = {'analysenumerique_001': ' BSc/French',
 'analysenumerique_002': 'BSc/French',
 'analysenumerique_003': 'BSc/French',
 'cpp_fr_001': 'Prop/French',
 'dsp_001': 'MSc/English',
 'dsp_002': 'MSc/English',
 'dsp_004': 'MSc/English',
 'dsp_005': 'MSc/English',
 'dsp_006': 'MSc/English',
 'geomatique_003': 'BSc/French',
 'hwts_001': 'BSc/French',
 'hwts_002': 'BSc/French',
 'initprogcpp_001': 'Prop/English',
 'microcontroleurs_003': 'BSc/French',
 'microcontroleurs_004': 'BSc/French',
 'microcontroleurs_005': 'BSc/French',
 'microcontroleurs_006': 'BSc/French',
 'progfun_002': 'BSc/French',
 'progfun_003': 'BSc/French',
 'structures_001': 'BSc/French',
 'structures_002': 'BSc/French',
 'structures_003': 'BSc/French',
 'venture_001': 'BSc/English',
 'villesafricaines_001' : 'Prop/French',
 'villesafricaines_002': 'Prop/French',
 'villesafricaines_003': 'Prop/French'}

no_quizzes_course = {'analysenumerique_001': '36-40',
 'analysenumerique_002': '36-40',
 'analysenumerique_003': '36-40',
 'cpp_fr_001': '06-10',
 'dsp_001': '36-40',
 'dsp_002': '36-40',
 'dsp_004': '36-40',
 'dsp_005': '36-40',
 'dsp_006': '36-40',
 'geomatique_003': '26-30',
 'hwts_001': '06-10',
 'hwts_002': '06-10',
 'initprogcpp_001': '11-15',
 'microcontroleurs_003': '16-20',
 'microcontroleurs_004': '16-20',
 'microcontroleurs_005': '16-20',
 'microcontroleurs_006': '16-20',
 'progfun_002': '01-05',
 'progfun_003': '01-05',
 'structures_001': '06-10',
 'structures_002': '06-10',
 'structures_003': '06-10',
 'venture_001': '06-10',
 'villesafricaines_001' : '16-20',
 'villesafricaines_002': '16-20',
 'villesafricaines_003': '16-20'}

no_weeks_course = {'analysenumerique_001': '09',
 'analysenumerique_002': '09',
 'analysenumerique_003': '09',
 'cpp_fr_001': '10',
 'dsp_001': '10',
 'dsp_002': '10',
 'dsp_004': '10',
 'dsp_005': '10',
 'dsp_006': '10',
 'geomatique_003': '11',
 'hwts_001': '05',
 'hwts_002': '05',
 'initprogcpp_001': '08',
 'microcontroleurs_003': '10',
 'microcontroleurs_004': '10',
 'microcontroleurs_005': '10',
 'microcontroleurs_006': '10',
 'progfun_002': '07',
 'progfun_003': '07',
 'structures_001': '10',
 'structures_002': '10',
 'structures_003': '10',
 'venture_001': '07',
 'villesafricaines_001' : '12',
 'villesafricaines_002': '12',
 'villesafricaines_003': '12'}